export type AnalysisStrategy =
  | "smc"
  | "chart_patterns"
  | "candlestick_reversals"
  | "combined"
  | "signals";

export interface StrategyDefinition {
  id: AnalysisStrategy;
  label: string;
  shortLabel: string;
  description: string;
  systemInstructions: string[];
  requiredEvidence: string[];
  supportedTimeframes: string[];
}

export type PriceLevelType =
  | "support"
  | "resistance"
  | "order_block"
  | "fair_value_gap"
  | "liquidity"
  | "invalidation"
  | "target"
  | "other";

export interface PriceLevel {
  label: string;
  price: number;
  timeframe: string;
  levelType: PriceLevelType;
  evidence: string;
  confidence: number;
}

export interface TradeScenario {
  name: string;
  direction: "bullish" | "bearish";
  trigger: string;
  /**
   * Concrete execution price for the primary setup. Required so the terminal can
   * show a tradable level and size a position against a real stop distance.
   */
  entryPrice: number | null;
  /** Order type the trader should actually place. */
  orderType: "market" | "limit" | "stop" | "none";
  /**
   * Where to hang the entry order. Typically a resting limit at a discount for
   * a pullback entry, or above/below for a breakout stop.
   */
  limitPrice: number | null;
  invalidationPrice: number | null;
  targetPrices: number[];
  /** Plain-language meaning of each target, e.g. "TP1 - partial at 1R". */
  targetRationale: string[];
  rationale: string;
  tradePlan?: TradePlan;
}

export interface ReasoningItem {
  observation: string;
  interpretation: string;
  timeframe: string;
  evidenceSource: "chart_image" | "ohlc_data" | "user_drawing";
}

export interface ConfluenceFactor {
  name: string;
  contribution: number;
  evidence: string;
}

export interface ConfluenceScore {
  score: number;
  factors: ConfluenceFactor[];
}

/** Minimal symbol metadata shape needed for contract sizing. */
export interface SymbolMetaLike {
  symbol: string;
  category: "synthetic" | "forex" | "metals" | "crypto";
  decimals?: number;
  pipFactor?: number;
}

export interface AIDrawingSupportResistance {
  price: number;
  type: "support" | "resistance";
  label: string;
  strength?: "major" | "minor";
}

export interface AIDrawingTrendline {
  startPrice: number;
  endPrice: number;
  type: "support" | "resistance" | "trend";
  label: string;
}

export interface AIDrawingOrderBlock {
  high: number;
  low: number;
  type: "bullish_ob" | "bearish_ob";
  label: string;
}

export interface AIDrawingTradeSetup {
  direction: "long" | "short";
  entry: number;
  stopLoss: number;
  tp1: number;
  tp2?: number;
  tp3?: number;
  riskRewardRatio?: number;
}

export interface AIDrawingsData {
  supportResistance: AIDrawingSupportResistance[];
  trendlines: AIDrawingTrendline[];
  orderBlocks: AIDrawingOrderBlock[];
  tradeSetup: AIDrawingTradeSetup | null;
}

export interface AnalysisResult {
  status: "complete" | "insufficient_data" | "partial";
  bias: "bullish" | "bearish" | "neutral" | "undetermined";
  symbol: string;
  timeframe: string;
  summary: string;
  confluence: ConfluenceScore;
  keyLevels: PriceLevel[];
  scenarios: TradeScenario[];
  reasoning: ReasoningItem[];
  limitations: string[];
  /**
   * Deterministic execution plan. Computed in code from the validated scenario
   * and the trader's account settings, never generated by the model.
   */
  tradePlan?: TradePlan;
  /**
   * Visual chart drawing instructions generated by the AI (S/R lines, trendlines, order blocks, TP/SL setup).
   */
  aiDrawings?: AIDrawingsData;
  modelMetadata?: {
    modelName: string;
    tokensUsed?: number;
    latencyMs?: number;
    timestamp: string;
  };
}

/** Account settings the user controls, used only for position sizing. */
export interface RiskProfile {
  accountBalance: number;
  riskPercent: number;
  maxMarginFraction?: number;
}

export interface SizingLadderRow {
  accountBalance: number;
  lots: number;
  riskAmount: number;
  /** True when the size rounded down to 0.00 at this balance. */
  tooSmall: boolean;
}

export interface TakeProfitLevel {
  label: string;
  price: number;
  /** Reward-to-risk from entry to this target. */
  rr: number;
  /** Suggested fraction of the position to close here. */
  closePercent: number;
  rationale: string;
}

export interface TradePlan {
  direction: "bullish" | "bearish";
  orderType: "market" | "limit" | "stop" | "none";
  entryPrice: number;
  /** Resting order price, when orderType is limit or stop. */
  limitPrice: number | null;
  stopLossPrice: number;
  stopDistancePips: number;
  takeProfits: TakeProfitLevel[];
  /** Lots rounded down to the broker's lot step. */
  lots: number;
  accountBalance: number;
  riskPercent: number;
  /** Currency amount lost if the stop is hit. */
  riskAmount: number;
  pipValuePerLot: number;
  totalMargin: number;
  /** Reward-to-risk at TP1, the primary objective. */
  rr: number;
  /**
   * Lot size across a ladder of account balances. Lot size is a function of
   * account size, not of the chart, so the trader can read off the size that
   * matches their balance before committing.
   */
  sizingLadder: SizingLadderRow[];
  warnings: string[];
}

export interface AnalysisRequestPayload {
  snapshotId?: string;
  imageUrl?: string;
  imageBase64?: string;
  symbol: string;
  timeframe: string;
  strategy: AnalysisStrategy;
  customPrompt?: string;
  /**
   * Trader account settings, used to derive lot size deterministically in
   * position-sizing.ts. Omit to skip the trade plan.
   */
  riskProfile?: RiskProfile;
  chartContext?: {
    visibleRange?: { from: string | number; to: string | number };
    candleCount?: number;
    lastPrice?: number;
    highPrice?: number;
    lowPrice?: number;
    /**
     * Whether the supplied candles are real market data. When "simulated",
     * the model must describe the chart as hypothetical rather than reporting
     * levels as live market structure.
     */
    dataSource?: "live" | "simulated";
    candlesSample?: Array<{
      time: number | string;
      open: number;
      high: number;
      low: number;
      close: number;
      volume?: number;
    }>;
  };
}
